### ISSUE TITLE
Home page: Funding and Site revision form

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#1005]
I can suggest revisions to my site names and funding space types so that I can successfully submit data.
[Design here](https://share.goabstract.com/1e96b7f9-917a-4471-bbda-d42d46a63674)

- From the home page, I can click on a link in a slim info alert that takes me to this form to request changes to my ECE Reporter data.
- I can request site name changes
- I can request a site be removed from my management
- I can request a new site
- I can indicate additional funding space types my program should have access to (example: We have Part-time CDC in ECE Reporter but we also need full-time)
- I can indicate funding space types my program does not need access to

- Skylight can see the email and organization info of the user making the request to send follow ups to

<img width="1082" alt="Screen Shot 2021-01-07 at 5 55 31 PM" src="https://user-images.githubusercontent.com/63253539/103954118-8ace4580-5111-11eb-8d13-aa0841a15d2a.png">

- After submitting a request, the user sees a confirmation message:
<img width="1092" alt="Screen Shot 2021-01-07 at 5 55 41 PM" src="https://user-images.githubusercontent.com/63253539/103954125-915cbd00-5111-11eb-83fc-b2dac533a32e.png">

**Comment by RyanHansz** [comment]
@jlhogan made a placeholder ticket for the "request changes to your site and funding space types" form we talked about

**Comment by bamader** [comment]
@RyanHansz What do you think of a tabular format for the managed sites and requests to change their names? As I was mocking up the given design, I thought it might not be intuitive for users that they could change more than one site name per submission of the form, so I wanted to experiment with a tabular view that showed all the same info but had less hidden elements so the user could more clearly see all their requested changes at once. If you don't like it we can switch back, just wanted to propose the idea!

<img width="1110" alt="Screen Shot 2021-01-12 at 8 36 39 AM" src="https://user-images.githubusercontent.com/49412165/104321251-6081dc80-54b1-11eb-9681-28483d1359c6.png">

**Comment by bamader** [comment]
(I kept all the other sections the same in terms of design, btw)

**Comment by JordanGuinn** [comment]
## Testing Strategy
- [ ] All unit tests are passing
- [ ] All e2e tests are passing
- [ ] Ensure all migrations can be executed
- [ ] Ensure all migrations can be rolled back

**Comment by JordanGuinn** [comment]
@bamader I see one of the AC of this ticket is the following:

- Skylight can see the email and organization info of the user making the request to send follow ups to

But it doesn't look like we're programmatically tracking user data with the requests stored in each of these respective tables.  Maybe we add `author` (and potentially `createdAt` or something) to each of these tables and populate that too?

**Comment by bamader** [comment]
Re: testing comments:
1. Oh yeah good catch on the recording email info. I saw we had no programmatic record of contact info, so I wasn't sure how we wanted to do that. Storing the orgId of the user who submitted the request could fulfill the organization requirement, but then for the "contact" info portion, we could store the person's name? Is this what you meant by an `author` field? (And then of course a `requestDate` field is also easy to add).
2. WILL DESTROY THIS EXTRA SPACE 🔨 💥 
3. Good catch, I'll filter out the site writing for only those that aren't all empty strings.
4. So when Ryan, Julia, and I were initially talking through this ticket, the idea was actually to deliberately write all combinations into the DB, because it was "easiest" to just store the whole raw map that the user generated. But, at the same time, we should also be able to use the same function that gives us a user's initial funding space permissions to calculate a diff map and then only write those spaces that are different. That would take care of this comment, correct?
5. Based on initial conversations with Ryan, it was desired that this page be accessible *only* before submitting data. I think the intent was to force users to revise their site info and funding space permissions before they added or committed any data to them so that we wouldn't have to deal with as many incorrect submissions for wrong sites/spaces.

**Comment by jlhogan** [comment]
1) add authorId  which will be the authenticated user id
4) if it's easy enough to only write the diff, that's great. If not, it's kinda fine b/c duplicative funding spaces cannot be created (unique constraints on the table) so in practice it won't really make our lives harder
5) users wont know this will only be available before submitting data, so there's no forcing function. I don't see any harm in making it available post as well (remembering thatthis pre/post divide is temporary and not how app will exist beyond initial data collection) (also remembering a long-term solution for updating / creating app data will be required at some point -- admin UI for OEC users or something)

**Comment by bamader** [comment]
Got it, sounds good! I'll add in the metadata fields for requests and timebox a short period to see if I can write the funding spaces diff (otherwise I'll just keep what's there). @RyanHansz If you're okay with it, I can just use the same alert on post-submit that I do on pre-submit for where the revision form lives.

**Comment by JordanGuinn** [comment]
How are we gonna be using the entries in the `change_funding_space_request` table?  Like are we gonna be occasionally trying to blindly upsert/delete all the rows in that table directly into `funding_space`, or is a manual step to review each individual row gonna be involved?

Cuz agreed, the number of rows in `change_funding_space_request` doesn't matter much if we're gonna be doing the former, but I could _easily_ see this becoming a PITA if the latter.

**Comment by jlhogan** [comment]
nah right now we're just gonna be  reducing the overhead of a process that currently involves victoria getting an email, us looking in existing data in spreadsheets and the app, and then me using existing "automated" processes to create data. At some point we will need a solution that OEC can use to manage this data, and this is not it. when we get there it'd make sense to revisit exactly what the needs are. but imo this is sufficient for our current purposes
