### ISSUE TITLE
User getting "booted" from system while entering child records

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1050]
From user: 
> I have started putting in my records and have been booted out twice after putting in a couple of records. This is going to take forever if this continues.

**Comment by JordanGuinn** [comment]
Session timeout bumped to 60 mins - pausing on for now to see if that (hopefully) addresses this.

**Comment by JordanGuinn** [comment]
Note to self: There have been a bunch of refresh token validation errors in WingedKeys logs over the past several days, that may correlate to the issue at play here.  Probably worth checking out our IdentityServer [refresh token configuration](https://docs.identityserver.io/en/3.1.0/topics/refresh_tokens.html).

**Comment by JordanGuinn** [comment]
Additional note to self: This appears to happen because at times ECE Reporter is hitting the IdentityServer's `/connect/token` endpoint to refresh the user's access token twice **at the exact same time**.  The first request succeeds, getting the user a new access token _and_ refresh token, then the second request fails, because it uses the now-invalidated refresh token.  And of course that second failure results in us auto-logging the user out.

Now it's just a matter of figuring out what causes the `connect/token` endpoint to be hit twice at the same time.
