### ISSUE TITLE
Tableau?

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1113]
Kate from Uconn made it sound like Tableau is the tool they use.
Do they have an account we can get some seats on? Or is this hypothetical?
Has Rachel officially landed on Tableau as the thing?

**Comment by jay-finch** [comment]
## 2:30 Executive Strategy Meeting (1/25/2021) Update
**Q: Does OEC currently have licenses?**
A: Per Rachel, no.  

**Q: Is the OEC planning to get licenses?**
A: Most likely.  Rachel wants to do an analysis of alternatives but since (a) the UConn team already has access and uses Tableau and (b) other CT government offices use Tableau, Rachel believes that Tableau is most likely.
