### ISSUE TITLE
Integrated funding work with ThirdSector

### ISSUE THREAD

**Issue by victoriasuwardiman** [ctoec/data-collection#1115]
Last we heard I believe they were hoping to bring something to this legislative session. Wondering if that's the case and if/how that could affect funding reports/data collection. Ask Rachel?

**Comment by jay-finch** [comment]
## 2:30 Executive Strategy Meeting (1/25/2021) Update
- Rachel says that Third Sector is blocked by the budget process.  She is thinking through the path forward on this.
- I think this is a low probability outcome for 2021 and we should assume no unless she says otherwise
- We can re-engage Third Sector as Rachel is aware
