### ISSUE TITLE
Add webinar videos to Help page

### ISSUE THREAD

**Issue by victoriasuwardiman** [ctoec/data-collection#1140]
If possible, embed webinar videos on Help page: https://ece-reporter.ctoec.org/help. 
**Update: embedding on https://help.ece-reporter.ctoec.org/ instead

Session #1: https://drive.google.com/file/d/1S1TJ5faVOuaEDGoQY2BN1rQt9ACe491O/view?usp=sharing 

Session #2 coming soon (2/3/2021)
**Update: embedding the second video only

**Comment by JordanGuinn** [comment]
Are there gonna be designs that come along with this, or should we play around with it a bit?

**Comment by victoriasuwardiman** [comment]
I'm inclined to say y'all got this but since we still have @RyanHansz! @RyanHansz, any chance you can do a quick mockup of how embedded videos might look best on the help page? Also, any other thoughts you have are welcomed!

**Comment by RyanHansz** [comment]
I'd recommend we just choose the best one (I assume I'll do better the second round :) ) and have it live on the homepage.@victoriasuwardiman does this location on the homepage make sense to you?
<img width="901" alt="Screen Shot 2021-02-02 at 9 17 44 AM" src="https://user-images.githubusercontent.com/63253539/106612867-90b01e80-6537-11eb-827c-e8583bb198e4.png">

Otherwise, I think it's a straightforward iframe embed, maybe some CSS to scale with the browser if you'd like to get fancy!
https://thisisa.blog/how-to-embed-media-github-pages

**Comment by RyanHansz** [comment]
Want to avoid this scenario on small screens:
<img width="491" alt="Screen Shot 2021-02-02 at 9 20 11 AM" src="https://user-images.githubusercontent.com/63253539/106613164-e5ec3000-6537-11eb-9c4a-a30217d5a6a5.png">

**Comment by victoriasuwardiman** [comment]
oh I was thinking on the in-app Help page not our documentation site, but I like this too! Ok yeah, we'll embed the one video. 

I can probably figure that out then @JordanGuinn so disregard this!
