### ISSUE TITLE
Better funding reporting period mapping in Upload

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1194]
## Background
Currently, reporting periods in `mm/dd/yyyy` format are mapped to whatever is the corresponding `mm/yyyy` version. 

However, reporting periods have start/end dates that do not perfectly align with months and so this can result in a row having a first funding period that ends before the enrollment start date if for example the enrollment starts at the end of a month (eg. 03/31/2020), and the reporting period for the corresponding month (03/2020) ends before that date (03/27/2020). This is completely opaque to users, and hard to fix.

## Acceptance Criteria
- When parsing reporting periods, if they are in `mm/dd/yyyy` format, instead of just grabbing `mm/yyyy` from the date, look for the reporting period in the system that includes the specific date

**Comment by bamader** [comment]
Gross thought here: because of serial number conversion magic, anyone that uploads a sheet using excel has all their dates automatically converted to numbers before it gets parsed by moment. We knew that. What I just realized during testing is that this means we don't ever actually get to see the string the user entered. So we don't know if their format was MM/YYYY or MM/DD/YYYY. For example, if we have the date value 03/01/2020 after moment parses the number, we don't know whether it came from the user input 03/01/2020 (in which case the 01 is meaningful and should stay) or from the user input 03/2020 (in which case the 01 was automatically added by moment because of the serialization). How should we handle this? It feels wrong to just assume that any funding period date that has an '01' in its day value just has a placeholder day. But also I don't think it's possible to recover the input string from the serialized number :/

**Comment by bamader** [comment]
Actually wait I was way overthinking this. We can just look for the reporting period that includes the specific date no matter what the user's input string was. If  they enter MM/DD/YYYY, the more specific date will be preserved when parsed as a moment so there's no issue. If they enter MM/YYYY, the day wasn't important anyway so it's not harmful to use the '01' that  gets auto parsed by Moment and Excel. This way we only alter map stuff and not the parse layer. Sorry if that was obvious to everyone else, I'm done having a brain fart now!

**Comment by jlhogan** [comment]
yup ^ you got it :)
