### ISSUE TITLE
As an OEC Admin User, I can view a table of all organizations

### ISSUE THREAD

**Issue by Derekskylight** [ctoec/data-collection#1278]
## Background
As an OEC Admin User, I can view a table of all organizations, along with their associated sites and funding spaces.

## Acceptance Criteria
- `Organizations` tab is the only tab present at the top of the page
   - `Users` tab to be added when we build that corresponding functionality
- Organizations SHOULD be present in the list view **whether or not** they have associated **funding spaces**
- Organizations SHOULD be present in the list view **whether or not** they have associated **sites**
- On login, OEC admin users are presented with a non-paginated list view of all organizations, displaying
   - Organization Name (not yet clickable)
   - Site count
   - Comma separated list of funding spaces

## Designs
[Admin Figma file](https://www.figma.com/file/GcYwZ05CjnG6QZNYlsCS1X/ECE-Reporter-%E2%80%93-Final-Designs?node-id=2%3A2)

![View Orgs.PNG](https://images.zenhubusercontent.com/602d78337403e44d7db5c4f3/7d56d7fd-c242-4d57-a7cd-6ea805284a63)

**Comment by JordanGuinn** [comment]
@Derekskylight @ehuang525 @jlhogan How do we want to handle site permissions independent of organization permissions here?

Let's say an admin user has permission to access **Organization 1** and **Organization 2** (and all the sites within), but also has permission to access **Site X**, which is associated with **Organization 3**.  The admin user does _NOT_ have explicit permission to access **Organization 3**, though.

In the scenario above, would we want to show **Organization 3** in this list view as well?  And if we do, would we want to show all the sites, or just the sites the admin user has permission to access?

**Comment by JordanGuinn** [comment]
We'll also want to think about whether or not that admin user should have the ability to **edit** said organization, but not for this ticket.

**Comment by ehuang525** [comment]
The admin user (the person seeing this view) should have access to all organizations since they are in charge of creating and editing organizations, as well as assigning permissions. They would see everything because they are the admin.

If I'm understanding the above use case correctly, if we're taking about the provider (the person who would then see the expression of these permissions in ECE Reporter), they would have to have access to Organization 3 in order to even have the ability to view a site that is part of Organization 3. So when the admin assigns permissions to a provider or organization, that specific site permission would be selected.

Does that help clarify?

**Comment by JordanGuinn** [comment]
Oh, right, duh.  Sorry, my brain broke there for a second 😅 Thanks Emily!

**Comment by JordanGuinn** [comment]
@Derekskylight @ehuang525 @jlhogan  Is the intention here that this takes the place of the current OEC admin overview UI that we already have in place?  Or rather that it sits alongside it?

#### Current Admin Overview Page
<img width="813" alt="Screen Shot 2021-05-06 at 3 23 12 PM" src="https://user-images.githubusercontent.com/8052350/117372803-fc7b8d80-ae7e-11eb-98fb-c28df9c6b07d.png">
