### ISSUE TITLE
Admin users can include sites during org creation

### ISSUE THREAD

**Issue by JordanGuinn** [ctoec/data-collection#1299]
## Background
During organization creation, OEC admin users will need the ability to add sites to be included within said organization.

## Acceptance Criteria
- `Sites` section is added to the OEC admin `Create Organization` view
- Users can add multiple sites to a single organization
- Fields included are outlined in the designs below
- Sites are saved to the organization once the entire form is submitted
   - Any errors preventing sites from being saved are bubbled up to the user

## Designs
[Full designs can be found in Figma](https://www.figma.com/file/GcYwZ05CjnG6QZNYlsCS1X/ECE-Reporter-%E2%80%93-Final-Designs?node-id=97%3A728).
![ECE Reporter – Create org.png](https://images.zenhubusercontent.com/6050f59bb12f6b5f4da9aeb1/d19622b1-5885-4d96-9b34-f3a167407442)

**Comment by bamader** [comment]
When creating sites, which fields do we need to enforce uniqueness on in the DB? (I.e. for organizations, we block the request to create an org if the name is taken; so for sites, which of their fields should block creation if it would duplicate something in the DB already) I'm guessing name only (because all of facility code, NAEYC ID, registry ID, and license number are optional) but thought this was worth checking.

Also, couple of questions about desired behavior in the app (do objects get created, what alerts if any should we show the user, etc.) for some different circumstances:
- What happens if one of the sites an admin enters can't be created, but other sites can (and the org name is available)?
- What happens if none of the sites an admin enters can be created, but the org name is available?

**Comment by JordanGuinn** [comment]
I think just `siteName` right now is fine regarding `Site` table column uniqueness (this should already be enforced at the database level anyway).

As far as situations where site(s) can't be created for whatever reason, I think our API layer should operate as our UX does and follow an `all-or-nothing` approach (_especially_ for **creating** new orgs), meaning if we can't create anything, we create nothing.  I don't have any specific ideas around what kind of error messaging/UX we'd want in these scenarios, though.

@Derekskylight @ehuang525 @jlhogan Any thoughts around UX error handling here?

**Comment by bamader** [comment]
That sounds good. And honestly, I kind of prefer the all-or-nothing approach, _especially_ for this ticket. Because we're working on base functionality now and I'd love to start parallelizing other work, I think doing an all or nothing approach would help get this ticket along. We can always fast follow with more complex behavior or different types of handling in a later ticket.

As far as error messages, my gut instinct was to use different status response errors to control which kinds of banner alerts get displayed in the client. That way, the prototype is already there for us right now, and we can still display custom messaging to the user while we figure out if we need to do anything more complex.

Pending any  extra design thoughts, I think that's what imma start with, and then we can adjust in PR review or a fast follows if need be!

**Comment by ehuang525** [comment]
Agree with the all-or-nothing approach. If some information is missing or cannot be completed then by default it's no use to create the organization.

I will drop some specific examples of field-level error handling in the Figma file! Ex: this organization name already exists, etc. I think that's enough to carry us forward for now and don't see the need to anything more complex than that.

**Comment by JordanGuinn** [comment]
@Derekskylight @ehuang525 @jlhogan  Thoughts on expected UX behavior _after_ an organization is created?  Should the user:

- See a successful org create message, then get routed back to the main org list view
- See a successful org create message, and stay on the org create view with a fully blank form

Or any other alternatives?

**Comment by ehuang525** [comment]
Ah yes, thanks for calling that out! I can work on getting some messaging and screens up on Figma for this. The first option sounds better to me since my current assumption is that the admin probably isn't creating organizations one after another all the time, therefore it doesn't warrant going back to the Create Org page.

**Comment by bamader** [comment]
In the PR I've got up right now, I send the user back to the main Organizations Table view with an alert banner up top letting them know the organization was successfully created. It felt like the very natural analogue of our create flow, where if a user hits the Add Record button, then after they submit that form they're sent to the Roster Table page with a success alert.

**Comment by ehuang525** [comment]
@bamader Perfect! That's basically what I was envisioning. Don't think we need anything fancy for this.
