### ISSUE TITLE
Admins can search for users by email from the org create view

### ISSUE THREAD

**Issue by JordanGuinn** [ctoec/data-collection#1310]
## Background
In order for OEC admins to be able to provide users access to the organizations they create, they first need a way to look users up (by **email** specifically).  Let's add a UX that allows for admins to do just that.

Of course, this ticket presupposes that there is actual email data to reference in the `User` table of ECE Reporter, which will be addressed in https://app.zenhub.com/workspaces/ece-dev-board-5ff506028d35f30012e0e937/issues/ctoec/data-collection/1313.

## Acceptance Criteria
- New `Users and permissions` section is added to the admin org create view, matching the designs specified below
- Admin users can look up users by email in the org create view
   - **Admin only** user search API is written
   - Search API requires an **exact** match to return applicable results
- The search response includes a **full count** of all user matches, as well as the **user emails** themselves
- Users can **NOT** yet _add_ users to organizations
   - To be implemented in a later ticket

## Designs
[Comprehensive FIGMA designs can be found here.](https://www.figma.com/file/GcYwZ05CjnG6QZNYlsCS1X/ECE-Reporter-%E2%80%93-Final-Designs?node-id=2%3A2)

#### Search
![Screen Shot 2021-05-05 at 1.01.23 PM.png](https://images.zenhubusercontent.com/5ff504ac246966652b569927/8f791509-9922-4f60-9a0e-9dc4e6c0486b)

#### Search Response
![Screen Shot 2021-05-05 at 1.01.34 PM.png](https://images.zenhubusercontent.com/5ff504ac246966652b569927/e22bb9f5-68bb-4302-bfe5-ffa8b0399d6a)

**Comment by JordanGuinn** [comment]
@ehuang525 @Derekskylight Do we want the user search UX in the create organization view to search by **exact** email matches, or **partial** email matches?

**Comment by Derekskylight** [comment]
I don't think we've come to a consensus on this topic, but I would argue exact search is the way to go:
1. It allows for an easier lift in dev (checking if strings are equal to one another as opposed to seeing if a string is contained within another string)
2. Similar to the image I attached from our Monday support requests, emails I've seen (going off Monday, no DB access) **don't** have multiple numbers in them or repetitions of names (i.e. 2 Derek Tam's in UIUC's system --> derekht@illinois.edu, derekht2@illinois.edu). Moreover, many of the email names are straightforward representations of their names in email format (flast@, first.last@, etc.). Due to this lack of complexity, I would trust users to be able to simply write down the email addresses fully. 
Let me know your thoughts @ehuang525 !
[<img width="139" alt="Exact Email Search" src="https://user-images.githubusercontent.com/79225819/117313197-ac3b0600-ae53-11eb-9122-2d82defbadb6.PNG">](url)

**Comment by ehuang525** [comment]
From my understanding, probably exact email. When I talked to @jlhogan it sounded like this was the only way to go - does that sound right to you too Julia?

**Comment by jlhogan** [comment]
depends what the resolution on https://github.com/ctoec/data-collection/issues/1313#issuecomment-833559581 is -- there's the possibility we can do fuzzy matching but i think for now let's just assume exact match
