### ISSUE TITLE
Clean up contents of admin overview page

### ISSUE THREAD

**Issue by Derekskylight** [ctoec/data-collection#1422]
## Background
Coming out of the Administrative onboarding sessions, several updates included in the overview page would lead to a smoother process for future usage by an OEC admin user.  Virtually all of the content captured in the screenshot below is already present on the page (save for the additional dashboard banner), so this is just a matter of reorganizing and rewording some of it.

## Acceptance Criteria
- Text banner directing users to the https://oecdata.org dashboard has been added
- Four horizontal, side by side boxes with text have been included with _sites, organizations, enrollments, and accounts created_ 
- Text header highlighting data collection status by site has been added
- Three horizontal, side by side boxes with text have been included with _in progress, completed, and no data entered._ 
- Upon login, the admin user now sees the 'In Progress' tab first instead of 'Completed'
- Registry ID has been added as an additional column

### Current Overview Page
![Screen Shot 2021-08-19 at 9.48.51 AM.png](https://images.zenhubusercontent.com/5ff504ac246966652b569927/70d2feeb-b840-4a6f-9773-292e6ee5c297)

### Updated Overview Page
![Admin Overview.PNG](https://images.zenhubusercontent.com/602d78337403e44d7db5c4f3/af8f4c51-0857-451a-b91b-175b516ddb34)

**Comment by JordanGuinn** [comment]
@Derekskylight @ehuang525 What constitutes `No data entered` here?  Like does that tab just include all the sites that have zero enrollments?

**Comment by JordanGuinn** [comment]
Also, since we're gonna be moving soon to get these data collection submissions onto a monthly cadence, will we want to update the information displayed here to always reflect the previous month?

**Comment by ehuang525** [comment]
@JordanGuinn That's how it currently is, I think. I left this up there since it seemed to provide information to OEC about whether certain sites may be inactive. If we get to build the feature for Admins to mark sites/orgs as inactive, then this may not be necessary.

And yes, I think it would make sense to update the information here to always reflect a monthly cadence as we move towards that. It would also reduce the need for us to manually update the text with each new round of data collection (assuming the rounds of data collection won't be lumped into a bunch of months anymore).

**Comment by JordanGuinn** [comment]
Oooooooo, I didn't realize most of this was already on the page - cool!
