### ISSUE TITLE
Inactive fundings should have gray BG in enrollment/funding section

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#273]
## Acceptance Criteria
- Change label to "inactive funding" and add light-gray background to funding cell BG
- Most recent/active funding should be on the top.

## Designs
<img width="1048" alt="Screen Shot 2020-09-04 at 12 23 34 PM" src="https://user-images.githubusercontent.com/63253539/92262666-7f3fe900-eea9-11ea-8ac4-1cf79689f3df.png">

**Comment by JordanGuinn** [comment]
## Testing Strategy
### General
- [ ] All unit tests are passing
- [ ] All e2e tests are passing

### Current Enrollment
- [ ] Most recent funding for the **current** enrollment is at the top
- [ ] Most recent funding for the **current** enrollment is not greyed out
- [ ] All other fundings for the **current** enrollment are sorted by first reporting period, with most recent closest to the top
- [ ] All other fundings for the **current** enrollment are greyed out

### Previous Enrollments
- [ ] Most recent funding for the **all previous** enrollments are at the top
- [ ] Most recent funding for the **all previous** enrollments are not greyed out
- [ ] All other fundings for **all previous** enrollment are sorted by first reporting period, with most recent closest to the top
- [ ] All other fundings for **all previous** enrollment are greyed out

**Comment by JordanGuinn** [comment]
@bamader Overall things are working as expected, just a couple things:

1. Don't know if this is intended or not, but the actual enrollment panel (containing site/model type/age group info) is _also_ greyed out for all previous enrollments.  I'll include a screenshot to clarify.
2. The border around funding cells is the exact same color as the gray background of inactive fundings, so it the border effectively vanishes for all inactive fundings.  I'll also make this clear in the screenshot.

![image.png](https://images.zenhubusercontent.com/5ff504ac246966652b569927/6bc950d8-576d-4e71-aa6f-2fc8e398c8f6)

**Comment by bamader** [comment]
@JordanGuinn 
1. Yep, this is desired! We want all historical/withdrawn enrollment blocks (enrollments + their fundings) to be our `secondary` gray color.
2. So I just played around with some inputs, and the problem is actually a little bit deeper than the color of the funding card. The real issue is that funding cards seem to have _no_ bottom border at all. This is why even in this historical enrollment block, you can see a gray dividing line between the enrollment card and the first funding card, but not between any of the funding cards. They've got top borders, but no bottoms. I'm happy to play around with the settings for those, but I want to wait for some weigh in from @RyanHansz or @victoriasuwardiman about whether individual funding cards should have bottom borders or whether they should appear as solid like this.

**Comment by jlhogan** [comment]
(IIRC, original designs had no border btwn fundings!)

**Comment by bamader** [comment]
Noice, then I think this is actually good to go?

**Comment by jlhogan** [comment]
I put a few comments on the PR when I reviewed; would like to see the date sort pulled out into util (or accomplished using existing util if there's one that will work), and if melanie's comment RE the moveNextRecord func is possible that would be nice too IMO

**Comment by bamader** [comment]
I saw and addressed your comments but I didn't see Melanie's--I'll go back and check out whether param passing solves.
