### ISSUE TITLE
Birth Certificates: I can enter data for US, non-US and unavailable birth certificates.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#325]
# [Updated designs](https://share.goabstract.com/ba1d8607-c43c-41e9-accf-37dfd45afafd)
<img width="662" alt="Screen Shot 2020-10-02 at 1 06 55 PM" src="https://user-images.githubusercontent.com/63253539/94950168-2a938c00-04b0-11eb-8b7a-652f3bd4b1ff.png">
<img width="457" alt="Screen Shot 2020-09-28 at 3 39 31 PM" src="https://user-images.githubusercontent.com/63253539/94478115-d2ebdc80-01a0-11eb-98ce-9c90cd22da9c.png">
<img width="442" alt="Screen Shot 2020-09-28 at 3 39 25 PM" src="https://user-images.githubusercontent.com/63253539/94478116-d3847300-01a0-11eb-931c-b67b8f2bc246.png">

Will require updates to the data spreadsheet template
– Birth Certificate type data element with acceptable values of US, non-US and unavailable
- Add unknown/not collected option to US birth certificate town and state
-- data is only required if US birth certificate

**Comment by bamader** [comment]
@RyanHansz What's the desired behavior if both town and the button for town unknown are filled in or not filled in? I ask because I'm trying to figure out the cleanest way to introduce an unknown button that also plays well with the validations (the other option being not having the button at all and just assuming we a blank space for town is "Unknown"). If we have both elements and both are filled in, do we assume the user actually means to take the value currently in Town, or do we throw an error? Similarly, if neither element is filled in, do we assume the user means unknown, or do we throw an error?

**Comment by RyanHansz** [comment]
The unknown button should clear any input in the related field. If the user types in the field again, the unknown button should switch to unselected. 

If either or both of the fields have no input, that should throw an error. The user needs to explicitly say the info is unknown, rather than just skip over it.
