### ISSUE TITLE
Duplicate alert messages and positioning

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#454]
<img width="1043" alt="Screen Shot 2020-10-01 at 9 39 06 AM" src="https://user-images.githubusercontent.com/63253539/94816607-0c536080-03ca-11eb-95cb-226e525e9f54.png">

<img width="1086" alt="Screen Shot 2020-10-01 at 9 54 23 AM" src="https://user-images.githubusercontent.com/63253539/94818430-1e360300-03cc-11eb-8292-b5e7a77304a4.png">

**Comment by mmazanec22** [comment]
I already had a PR up for the weird side by side positioning but I have q's about the other two things.
- In what case are you getting the duplicate alert on the roster?  Just when you navigate to the roster or after doing something or...?  I can't reproduce it and I don't see it in the code
- That screenshot shows the alert above the h1.  I just moved all of them below the h1 because of #395 .  Do they go above the header or below it?

**Comment by jlhogan** [comment]
I think the duplicate roster is just in QA and is on my feature branch, so will remove !
