### ISSUE TITLE
Adding a record has no finish button

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#483]
Currently:
<img width="1082" alt="Screen Shot 2020-10-02 at 2 22 51 PM" src="https://user-images.githubusercontent.com/63253539/94956836-d0e48f00-04ba-11eb-976d-2ac4cd12e88f.png">

Desired (add to bottom)
<img width="1014" alt="95211111-2a4e0600-07ba-11eb-9ce6-8a6d8395996a" src="https://user-images.githubusercontent.com/63253539/95242877-cd644700-07dd-11eb-8cbf-e390bb9e36f1.png">

**Comment by jlhogan** [comment]
Hey @RyanHansz -- when i go through the add record flow, after saving the last section, im automatically brought back to the roster, with an alert saying my record has been added. Is that not the desired experience? Is the ask here to change it so that a user has to press another button after completing?

**Comment by RyanHansz** [comment]
@jlhogan auto-submit with confirm alert is the desired experience. Looks like this issue got fixed somehow.
