### ISSUE TITLE
CSR has no valid reporting periods when adding a record or enrollment

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#485]
<img width="362" alt="Screen Shot 2020-10-02 at 2 27 49 PM" src="https://user-images.githubusercontent.com/63253539/94957305-86174700-04bb-11eb-9261-f200d8e08b17.png">

**Comment by RyanHansz** [comment]
This doesn't appear to be fixed, but added #674 to make sure we update all the funding reporting periods.

**Comment by jlhogan** [comment]
yeah no sorry, wouldn't expect this to be fixed in staging actually b/c the way we check for reporting periods to decide if we should create them or not.... but also the way we create reporting periods for staging/dev environments will not be the sme way they're created for prod so i think they can be considered separately. I'll go and drop the reporting periods from staging tho to make sure they get created there on next deploy!

**Comment by jlhogan** [comment]
actually JK im just going to create them in staging manually right now

**Comment by jlhogan** [comment]
alright, should be resolved in staging now
