### ISSUE TITLE
Improved error state for child records with missing enrollments and/or incomes

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#487]
## Background
The error state for child records with missing enrollments or income determinations is pretty vague, and doesn't supply the user with anything meaningful to take action.  We should provide more specific errors in these circumstances.

### When there are no enrollments (current or past) on a child record
- Add `At least one funded enrollment is required for each child record.` Error message and icon below the enrollment and funding header
- Expand add new enrollment form on opening the section
- Change button to say "add new enrollment"
- Remove the `Missing Enrollment` error banner alert, as this error will provide more specificity

### When there are enrollments (current or past) but no funding on a child record
-  Add `At least one funded enrollment is required for each child record.` Error message and icon below the enrollment and funding header
- Remove the `Missing Funding` error banner alert, as this error will provide more specificity
- Show the funding section of the card with error icons in each field
- Change the "start new funding" button link to "add funding info"

### When there are no income determinations (current or past) on a child record
- Add `A recorded income determination is required.` Error message and icon below the income section header
- Expand add new enrollment form on opening the section
- Change button to say "add new enrollment"

### When there are no enrollments (current or past) on a child record
![No Funded Enrollment.png](https://images.zenhubusercontent.com/5f6e38ea084e48ea4bed8071/f8fc39fe-dd42-43ee-ab71-17a067515ef3)
### When there are enrollments (current or past) but no funding on a child record
![No Funding.png](https://images.zenhubusercontent.com/5f6e38ea084e48ea4bed8071/1ad91199-6ff3-4e2d-ac5f-a625f8153839)

### When there are no income determinations (current or past) on a child record
![No Income.png](https://images.zenhubusercontent.com/5f6e38ea084e48ea4bed8071/bb330420-6dc2-4a32-85b6-c7f86c01e50a)

**Comment by RyanHansz** [comment]
Look up accessibility requirements for error/alert/label

**Comment by bamader** [comment]
Based on some design work and looking at our components, I changed two small things about how this ticket looks in implementation:

1) Based on talking to Victoria, I made the alert text for the case where there are enrollments that lack funding information read: `All enrollments must be associated with at least one funding.`
2) Also, for the case where there are enrollments that lack funding information, the "Add Funding Info" text didn't make sense to me in the third card row of the enrollment. That card is the Change Funding component, which is used to end fundings and switch to new ones. The card that actually shows the missing info alerts is the Edit Funding component, so it was not only more intuitive to me to put the "Add funding info" text there instead of the Change Funding component, but this also made the functionality of the cards line up more cleanly (since Change Funding cards aren't designed to allow inputting funding field information in the form).

Here's what that looks like in the tool: ![Screen Shot 2021-01-27 at 6.57.57 PM.png](https://images.zenhubusercontent.com/6007511fbd195723a29aa58b/e8f3297d-aa87-4129-8952-5d1e86ab073a)

Once a user fills in any requisite missing funding information, the usual styling of three cards (Enrollment, Edit Funding, and Change Funding) reappears.

I'll put more details in the PR I open for this ticket.
