### ISSUE TITLE
Create separate data samples for download

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#616]
1 – For programs to download in the app. Should not have any errors. See:
[This spreadsheet](https://docs.google.com/spreadsheets/d/14GLwMS2i6hzLDNZb1hKqeLmuQavKpgg7aiKOq83lrDE/edit#gid=0)

2 – For testing, a page only the team can access where we can download data to test with that has errors and other test scenarios. Use our existing sample data for now.

**Comment by mmazanec22** [comment]
@RyanHansz can you expand on what you want out of the complete data example?  Right now it's dynamically generated, which I think we want to keep rather than checking that file into source control/continuing to manually update a file.  Do we basically want to show all of the valid formats possible?

For the incomplete/bad fake data for testing... I imagine basically we want to be able to test with:
- upload in the totally wrong format-- wrong file type, no column headers, whatever
- upload with one column malformatted
- upload with lots of missing data
- upload with edge-case-y data

**Comment by RyanHansz** [comment]
@mmazanec22 I feel the goal of the sample data is to represent a realistic version of what someone may actually upload. 
The important things to show are:
- Consistent formatting (We can encourage default formats for each column even if we accept many different types)
- Show high-quality data (no empty values, few unknown/not collected rows)
- Show how to add a historical enrollment (Lester Wain Mattea in the example)
- Data without errors (funding types and space types are valid for age groups)

If its low-effort to programmatically generate a sample with these qualities, then that's ideal. Otherwise, I'm happy to keep this file updated manually, as we need example data to send in communications to programs in the next few weeks.

**Comment by RyanHansz** [comment]
And the fake testing data scenarios seem like a great starting point to me
