### ISSUE TITLE
Make file upload tests more robust

### ISSUE THREAD

**Issue by mmazanec22** [ctoec/data-collection#629]
After upload bugs are fixed, split upload tests into one that tests complete data upload and one that tests incomplete data upload.

**Comment by mmazanec22** [comment]
Note: we can use the existing file upload util and modify it to be able to go to the dev page in the front end and access the other fake data.  May need to make the fake data tests only run in non-prod-like envs.

**Comment by jlhogan** [comment]
these tests so far only run in non-prod-like envs so that should be fine.

**Comment by bamader** [comment]
What's the desired test behavior for uploading incomplete info? Since we don't know what field(s) or how many children the fake data generator will choose to make incomplete, do we just want to check for whether the error modal appears?

**Comment by jlhogan** [comment]
I dont know if using file upload in e2e is the best way to test this -- we should write backend unit-y tests for the parsing logic, and we should write some api tests to ensure validations work as expected

**Comment by bamader** [comment]
Not quite sure I understand this ticket, then. The initial description and comments about the file upload are e2e stuff, but it sounds like we actually want something different. Since we already have `map.test.ts` to test parsing each field, what exactly is the new add? @mmazanec22 Maybe you can clarify your intent since you opened the ticket?

**Comment by jlhogan** [comment]
the map stuff tests the mapping logic, but there are no tests for the parsing logic. I think this ticket was opened as a general placeholder to ensure we get test coverage. I was just sharing my opinion that (due to some of the limitations you pointed out) getting coverage for some of the specific stuff we may have been considering testing via upload tests could be better achieved through other types of tests. 

I think the AC here is just to have one test that uploads complete data, and ensures that you go the roster and one test that uploads incomplete data, ensures you get the error modal, and then go to the roster and have a missing info error alert. 

More specific fine grained testing can happen via the other methods I mentioned.

**Comment by bamader** [comment]
Ah okay,  I understand now. Thanks for the context, Julia. So what I'm hearing is that we need two kinds of tests:
1) a broad "incomplete data upload" test that uses the file upload util, in which we upload  the file, expect the error modal, and confirm a missing info alert appears on the roster
2) more finer-toothed tests (which should be api / backend unit-y tests) that check individual parsing logic, with the  goal of making sure that incomplete data triggers the validations  we expect to see.
This ticket seems  dedicated to handling type 1, so we  can open another ticket for type  2 (which I'm  also  happy to work on because type 1 is pretty simple to write).
