### ISSUE TITLE
Select a data table framework

### ISSUE THREAD

**Issue by julyytran** [ctoec/data-collection#65]
ryans research: https://github.com/ctoec/data-collection/issues/51

**Comment by JordanGuinn** [comment]
**### IN PROGRESS**

### **Interactions to Support**
The following interactions were taken into consideration when determining which library to choose:

- In-place editing
- In-place input validation
- Bulk operations
- Bidirectional sort across columns
- Material design

**### Libraries Explored**
The following list represents all of the libraries I've explored in some capacity, listed in no particular order:

- [React Base Table](https://github.com/Autodesk/react-base-table)
- [React Table](https://github.com/tannerlinsley/react-table)
- [React Data Table Component](https://github.com/jbetancur/react-data-table-component)
- [React Data Grid](https://github.com/adazzle/react-data-grid)
- [Material Table](https://github.com/mbrn/material-table)
- [MUI Datatables](https://github.com/gregnb/mui-datatables)

**### Findings**
**React Base Table**
This Autodesk library seemed like a solid contender on it's face, but after digging in a bit, it turns out it doesn't offer a couple of important UX pieces that we need (namely bulk operations).  It's also just kinda ugly, to be quite frank.

**React Table**
So this library is actually "headless", meaning it doesn't come with any actual components or corresponding styles out of the box.  This would be perfect if we have the time and bandwidth to apply our own custom designs (to be more consistent with USWDS patterns), but I don't think that's a reality we're currently a part of.

**React Data Table Component**
One of the nice things about this library is its support for Material design, and the general look and feel of the table's individual elements.  Unfortunately, it appears to only provide read-only components, which isn't going to cut it for our purposes.

**React Data Grid**
Right off the bat, this library appears to have pretty solid community support/usage, and also checks off most of the functional boxes we require.  The biggest downside in my opinion here is just with the overall UX - it doesn't support Material design, and just feels somewhat clunky in comparison.

**Material Table**
The de-facto complementary project for advanced use cases on Material UI’s [official website](https://material-ui.com/components/tables/#complementary-projects).  So far doesn't seem to have any notable issues.  In progress.

**MUI Datatables**
One of the runners-up on Material UI’s official website.  Also doesn't appear to have any real problems.  In progress.
