### ISSUE TITLE
Allow SHS spaces to be entered without an overall capacity #.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#684]
Any user with SHS funding should be able to choose SHS funding options for an enrollment.

On the roster, SHS should not show # enrolled/# capacity, just # enrolled.

**Comment by jlhogan** [comment]
should be able to choose _any_ SHS funding options? i.e. all of  
```
ExtendedDay = 'Extended-day',
  ExtendedYear = 'Extended-year',
  ExtendedDayYear = 'Extended day/year',

  AdditionalFull = 'Additional full-day/full-year',
  AdditionalSchool = 'Additional school-day/school-year ',
  AdditionalExtendedSchool = 'Additional school-day/school-year/extended-year',
```

**Comment by jlhogan** [comment]
for whoever picks this up; since SHS has no capacity, thoughts on using `-1` as a value to indicate capacity-less fundings?

**Comment by RyanHansz** [comment]
> should be able to choose _any_ SHS funding options? i.e. any of
> 
> ```
>   ExtendedDay = 'Extended-day',
>   ExtendedYear = 'Extended-year',
>   ExtendedDayYear = 'Extended day/year',
> 
>   AdditionalFull = 'Additional full-day/full-year',
>   AdditionalSchool = 'Additional school-day/school-year ',
>   AdditionalExtendedSchool = 'Additional school-day/school-year/extended-year',
> ```

Yes. Unless we can get some feedback from actual programs with SHS funding that say otherwise. 🤷‍♂️

**Comment by mmazanec22** [comment]
@RyanHansz is it that they *can* be entered without overall capacity, or that they *definitely should* be entered without overall capacity?

**Comment by jlhogan** [comment]
there is no capacity for SHS -- so this is really just a display change. If we're listing out SHS "utilization", it's just a straight # of funded kids, there will be never a ratio "out of this many spaces" b/c SHS funding is not allocated on a space basis. 

To that end, I was thinking we could just put the capacity as -1 or 0 so that instead of having SHS-specific logic (possible other fundings end up going this way? and we need to have a capacity value anyway, we just have logic that says "if the capacity is < 0 (or capacity === 0 depending on what we choose), then def don't display this as a ratio"
