### ISSUE TITLE
Add "name" or "row #" column to missing info modal when batch uploading.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#722]
<img width="1010" alt="Screen Shot 2020-11-23 at 9 18 49 AM" src="https://user-images.githubusercontent.com/63253539/99972746-e95f8000-2d6c-11eb-83a8-6084b5d1842d.png">
- Offset based on the template the user is using (excel or .csv)

**Comment by bamader** [comment]
@RyanHansz In your opinion, how likely do you think providers are to be uploading sheets with historical data? Because our error checking operates on child records instead of spreadsheet rows, it's proving pretty tricky to give accurate row numbers for historical enrollments because they introduce so much variability (they could be non-consecutive, update existing enrollments/fundings, define new enrollments/fundings). The options I can see are: 1) use precise row numbers (I think it's doable, but it might involve some messy tracking), 2) use row number ranges (i.e. for each error that occurs, give all the rows of the child in which the error occurs), or 3) just use child names. Wanted to check in before I went too deep down the rabbit hole. Thoughts?

**Comment by RyanHansz** [comment]
@bamader good call out. Let's avoid this rabbit hole and just use child names. Start with 5 names then truncate:
[Child first/last name], [Child first/last name], [Child first/last name], [Child first/last name], [Child first/last name],  and [#] more children

**Comment by bamader** [comment]
Sounds good.  I tried playing around with precise row numbers a little more just to  see if I'd missed something,  but there's some messy and brittle strings  that aren't robust to re-ordering rows so  this avenue doesn't seem worth it (at least not right now). Child names are the easiest option though because they come nested with each validation error, so this should be up this afternoon!
