### ISSUE TITLE
zipcodes are being parsed wrong again

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#829]
01920 in spreadsheet becomes long negative # in staging

add a test!!

**Comment by bamader** [comment]
Figured this out. During one of the form refactors, the zipcode field on the Family entity was changed from `zipcode` to `zipCode`, but the check within `parse.ts` that calls the zip code helper function was never updated to reflect the capitalization. Do we still think we need a test for this since it was just a letter being off in the `if (prop === ...)`?

**Comment by jlhogan** [comment]
yes because a test would have caught that before we pushed it to a live environment ! but wonderful that it can be a simple test

**Comment by bamader** [comment]
Is it okay if I include a `ZipCode_Test` spreadsheet in the e2e tests folder then? Easiest way I can think of to test the zipcode parsing is uploading a one-record file and confirming the zip code on the Family Address page of EditRecord.
