### ISSUE TITLE
Better handle uploaded funding periods with dates before 07/2020

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#905]
Currently, when I upload a first funding reporting period with a date before 07/2020, I get an error because ECE Reporter does not have historical funding reporting periods.

Instead of an error, we can:
- Add historical reporting periods using CDC dates (it's okay if we're ignoring slight differences for different funding streams)
- Create a 'before July 2020' funding reporting period option
- Automatically match any date before 07/2020
-  to that option
- Remove "Record 07/2020 for any child whose funding began in or before July 2020." on data definitions table

**Comment by atreni** [comment]
Julia and I discussed this morning, and think it would be valuable for users to be able to include enrollment dates before July 2020 (this is only a requirement for OEC, but does need to be a system requirement). Thanks to @victoriasuwardiman for pulling up the past CDC reporting periods and formatting them for us to use! @jlhogan let me know if you need any other information in order to create this update. I think we probably only need to go back as far as September 2 - 27 reporting period. Thank you!

July 1, 2019 - July 26, 2019
July 29, 2019 - August 30, 2019
September 2, 2019 - September 27, 2019
September 30, 2019 - October 25, 2019
October 28, 2019 -  November 29, 2019
December 2, 2019 - December 27, 2019
December 30, 2019 - January 31, 2020
February 3, 2020 - February 28, 2020
March 2, 2020 - March 27, 2020
March 30, 2020 - April 24, 2020
April 27, 2020 -May 29, 2020
June 1, 2020 -June 26, 2020

**Comment by jlhogan** [comment]
Reporting periods for all funding streams back to july 2019 have been created in ECE Reporter v2 prod. @RyanHansz -- we need to remove content / copy around using 07/2020 in place of real reporting periods for funding. I'm not sure of everything that needs to change, beyond removing the alert from the data defn table.

**Comment by RyanHansz** [comment]
Added a note to remove that alert in the ticket description. The only other place it lives is the help content, which I can change

**Comment by RyanHansz** [comment]
@jlhogan can we add the same reporting periods in staging? It would make testing easier and more consistent
